name: CI/CD Flask app to Amazon EC2 - Flasktice

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: |
             echo "Hello world"
             pwd
             ls
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye World
        run: echo "Goodbye World"
        shell: bash
        
